---
rule_id: 13
key: known_weak_cipher_negotiated
group_id: 1
group: tls_negotiation
label_as: Known weak ciphers negotiated {negotiated_cipher} ({negotiated_cipher_bits} bits)
issue: |-
  A cipher suite is a combination of authentication, encryption, and message authentication code (MAC) algorithms
  They are used during the negotiation of security settings for a TLS/SSL connection as well as for the transfer of data
  By default, most servers still support outdated and known vulnerable ciphers
  This is known as an insecure default and could lead to trivial attacks against default or misconfigured servers
cvss2: AV:N/AC:H/Au:N/C:C/I:C/A:N
cvss3: AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N
cve:
  - CVE-2014-6321
  - CVE-2008-0166
threats:
  "MITRE ATT&CK":
    - version: 11.2
      tactics:
        - TA0043
        - TA0007
        - TA0009
      data_sources:
        - DS0035
        - DS0028
        - DS0006
      techniques:
        - T1119
        - T1185
        - T1189
        - T1190
      sub_techniques:
        - parent: T1134
          id: "001"
        - parent: T1087
          id: "002"
        - parent: T1595
          id: "002"
        - parent: T1071
          id: "001"
        - parent: T1584
          id: "006"
        - parent: T1556
          id: "005"
        - parent: T1550
          id: "001"
      mitigations:
        - M0942
        - M0937
        - M0913
        - M0916
compliance:
  "NIST SP800-131A":
    - version: "strict mode"
    - version: "transition mode"
  "FIPS 140-2":
    - version: "Annex A"
  "PCI DSS":
    - version: "3.2.1"
      requirements:
        - 4.1
    - version: "4.0"
      requirements:
        - 1.2.6
        - 2.2.4
        - 2.2.5
        - 4.2.1
        - 6.2.4
        - 12.3.3
references:
  - name: Testing for Weak SSL TLS Ciphers Insufficient Transport Layer Protection (WSTG-CRYP-01)
    url: https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/09-Testing_for_Weak_Cryptography/01-Testing_for_Weak_Transport_Layer_Security
anotate_results:
  - result_value: False
    result_level: pass
    display_as: Good Configuration
    score: 75
  - result_value: True
    result_level: fail
    display_as: Misconfigured
    score: -200
substitutions:
  - negotiated_cipher
  - negotiated_cipher_bits
