stages:
  - tests
  - pre-deploy
  - deploy
  - post-deploy

sast black:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - pre-commit run black --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
  only:
    refs:
      - merge_request
      - main

sca pip-audit:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - pre-commit run pip-audit --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
  only:
    refs:
      - merge_request
      - main

secrets scanning:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - |+
      TOOLS="detect-private-key detect-secrets"
      for i in $TOOLS
      do
        pre-commit run $i --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
      done
  only:
    refs:
      - merge_request
      - main

repo checks:
  stage: tests
  tags:
    - trivialscan
  script:
    - echo $CI_COMMIT_MESSAGE > commit-msg.txt
    - pre-commit run conventional-pre-commit --hook-stage commit-msg --commit-msg-filename commit-msg.txt --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
    - |+
      TOOLS="no-commit-to-branch mixed-line-ending check-merge-conflict"
      for i in $TOOLS
      do
        pre-commit run $i --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
      done
  only:
    refs:
      - merge_request
      - main

python syntax:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - |+
      TOOLS="check-ast debug-statements check-builtin-literals"
      for i in $TOOLS
      do
        pre-commit run $i --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
      done
  only:
    refs:
      - merge_request
      - main

whitespace:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - |+
      TOOLS="remove-tabs trailing-whitespace"
      for i in $TOOLS
      do
        pre-commit run $i --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
      done
  only:
    refs:
      - merge_request
      - main

yaml json py linting:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - |+
      TOOLS="prettier typos pretty-format-json check-json check-yaml"
      for i in $TOOLS
      do
        pre-commit run $i --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
      done
  only:
    refs:
      - merge_request
      - main

twine check:
  stage: pre-deploy
  tags:
    - trivialscan
  script:
    - make build check
  only:
    refs:
      - merge_request
      - main

publish pypi:
  stage: deploy
  tags:
    - trivialscan
  script:
    - make build check pypi
  only:
    refs:
      - main

git tag:
  stage: post-deploy
  tags:
    - trivialscan
  script:
    - make tag
  only:
    refs:
      - main
