stages:
  - tests
  - build
  - deploy

test:sast:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - pre-commit run black --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
  only:
    refs:
      - merge_request
      - main

test:sca:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - pre-commit run pip-audit --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
  only:
    refs:
      - merge_request
      - main

test:secrets:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - |+
      TOOLS="detect-private-key detect-secrets"
      for i in $TOOLS
      do
        pre-commit run $i --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
      done
  only:
    refs:
      - merge_request
      - main

test:git:
  stage: tests
  tags:
    - trivialscan
  script:
    - echo $CI_COMMIT_MESSAGE > commit-msg.txt
    - pre-commit run conventional-pre-commit --hook-stage commit-msg --commit-msg-filename commit-msg.txt --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
    - |+
      TOOLS="no-commit-to-branch mixed-line-ending check-git-config-email check-merge-conflict"
      for i in $TOOLS
      do
        pre-commit run $i --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
      done
  only:
    refs:
      - merge_request
      - main

test:syntax:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - |+
      TOOLS="check-ast debug-statements check-builtin-literals typos pretty-format-json check-json check-yaml remove-tabs trailing-whitespace"
      for i in $TOOLS
      do
        pre-commit run $i --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
      done
  only:
    refs:
      - merge_request
      - main

test:style:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - |+
      TOOLS="remove-tabs trailing-whitespace"
      for i in $TOOLS
      do
        pre-commit run $i --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
      done
  only:
    refs:
      - merge_request
      - main

test:linting:
  stage: tests
  tags:
    - trivialscan
  allow_failure: true
  script:
    - |+
      TOOLS="prettier typos check-json check-yaml"
      for i in $TOOLS
      do
        pre-commit run $i --local-branch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_BRANCH}
      done
  only:
    refs:
      - merge_request
      - main

test:package:
  stage: build
  tags:
    - trivialscan
  script:
    - make build check
  only:
    refs:
      - merge_request
      - main

publish:pypi:
  stage: deploy
  tags:
    - trivialscan
  script:
    - make build check publish
  only:
    refs:
      - main
