stages:
  - tests
  - build
  - deploy

test:wheel:
  tags:
    - linode
  stage: tests
  script:
    - make check
  only:
    refs:
      - merge_request
      - main

build:wheel:
  tags:
    - linode
  stage: build
  script:
    - make build
  only:
    refs:
      - merge_request
      - main

publish:pypi:
  tags:
    - linode
  stage: deploy
  script:
    - make publish
  only:
    refs:
      - main
