---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
        files: src
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-added-large-files
      - id: check-builtin-literals
        args: ["--no-allow-dict-kwargs"]
      - id: debug-statements
      - id: no-commit-to-branch
        stages: [commit]
        args: [--branch, master]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.12.3
    hooks:
      - id: check-git-config-email
        args: ["--domains", "trivialsec.com"]

  - repo: https://github.com/crate-ci/typos
    rev: v1.7.0
    hooks:
      - id: typos
        files: src

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: src

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: src

  - repo: local
    hooks:
      # - id: pylint
      #   name: pylint
      #   entry: pylint
      #   language: system
      #   types: [python]
      #   require_serial: true
      - id: pip-audit
        name: pip-audit
        language: system
        entry: pip-audit
        args: [-r]
        types: [plain-text, non-executable, file]
        files: ^(requirements)\.(txt)$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        language: python
        entry: detect-secrets-hook
        args: ["--baseline", ".secrets.baseline"]
