---
defaults:
  use_sni: True
  cafiles:
  client_pem:
  tmp_path_prefix: /tmp

outputs:
  - type: console
  - type: json
    path: .development/trivialscan_results.json

# targets:
#   - hostname: expired.badssl.com
#     client_certificate: False
#     skip_evaluations:
#     skip_evaluation_groups:

evaluations:
  - key: client_renegotiation
    label_as: Client initiated TLS renegotiation (insecure)
  - key: secure_renegotiation
    label_as: Client initiated TLS renegotiation (secure)
