---
defaults:
  use_sni: True
  cafiles:
  tmp_path_prefix: /tmp
  http_request_path: /
  # skip_evaluations:
  #   - revocation_crlite
  #   - tls_robot
  #   - dnssec
  #   - deprecated_dnssec_algorithm
  #   - private_key_known_compromised

outputs:
  - type: console
  - type: json
    path: .development/results/{date_iso8601}.json
  - type: json
    path: .development/results/{date_year}-{date_month}-{date_day}.json
  - type: json
    path: .development/results/all.json

"PCI DSS 3.2.1":
  "6.5.4": Insecure communications

targets:
  - hostname: client.badssl.com
    client_certificate: .development/badssl.com-client.pem
  - hostname: expired.badssl.com
    skip_evaluations:
      - client_renegotiation
    skip_evaluation_groups:
      - dns_configuration
  - hostname: tls-v1-1.badssl.com
    port: 1011
  - hostname: wrong.host.badssl.com
  - hostname: untrusted.root.badssl.com
  - hostname: no-subject.badssl.com
  - hostname: revoked.badssl.com
  - hostname: incomplete-chain.badssl.com
  - hostname: no-sct.badssl.com
  - hostname: cbc.badssl.com
  - hostname: superfish.badssl.com
  - hostname: www.ssllabs.com
    http_request_path: /ssltest/analyze

# Customise outputs, or really anything
evaluations:
  # substitute a value into the output label
  - key: secure_renegotiation
    label_as: Client initiated TLS secure renegotiation {preferred_protocol}
    substitutions:
      - preferred_protocol

  # reverse the result, so a trusted russian root is a FAIL instead of a PASS
  - key: trust_russian
    anotate_results:
      - value: True
        evaluation_value: "[light_coral]FAIL![/light_coral]"
        display_as: Trusted
        score: -100
      - value: False
        evaluation_value: "[dark_sea_green2]PASS![/dark_sea_green2]"
        display_as: Not Trusted
        score: 100
