---
defaults:
  use_sni: True
  cafiles:
  tmp_path_prefix: /tmp
  skip_evaluations:
    - revocation_crlite

outputs:
  - type: console
  - type: json
    path: .development/trivialscan_results.json

"PCI DSS 3.2.1":
  12.7: To minimise the risk of attack from local sources, run a history scan of candidates before hiring

targets:
  - hostname: expired.badssl.com
    port: 443
    client_certificate:
    skip_evaluations:
      - client_renegotiation
    skip_evaluation_groups:
      - dns_configuration
  - hostname: self-signed.badssl.com
  - hostname: wrong.host.badssl.com
  - hostname: no-common-name.badssl.com
  - hostname: untrusted.root.badssl.com
  - hostname: no-subject.badssl.com
  - hostname: revoked.badssl.com
  - hostname: pinning-test.badssl.com
  - hostname: incomplete-chain.badssl.com
  - hostname: sha1-intermediate.badssl.com
  - hostname: no-sct.badssl.com
  - hostname: invalid-expected-sct.badssl.com
  - hostname: null.badssl.com
  - hostname: cbc.badssl.com
  - hostname: rc4-md5.badssl.com
  - hostname: rc4.badssl.com
  - hostname: 3des.badssl.com
  - hostname: static-rsa.badssl.com
  - hostname: sha1-2016.badssl.com
  - hostname: tls-v1-0.badssl.com
    port: 1010
  - hostname: tls-v1-1.badssl.com
    port: 1011
  - hostname: superfish.badssl.com
  - hostname: edellroot.badssl.com
  - hostname: dsdtestprovider.badssl.com
  - hostname: preact-cli.badssl.com
  - hostname: webpack-dev-server.badssl.com

# Customise outputs, or really anything
evaluations:
  - key: client_renegotiation
    label_as: Client initiated TLS renegotiation
    anotate_results:
      - value: False
        score: 80

  - key: secure_renegotiation
    label_as: Client initiated TLS secure renegotiation {preferred_protocol}
    substitutions:
      - preferred_protocol
